name: Rebuild Dist

on:
  push:
    branches:
      - master
      - v2.x

env:
  CI: true

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Push changes
        uses: actions-go/push@v1
        with:
          author-name: ${{ github.actor }}
          author-email: ${{ github.actor }}@users.noreply.github.com
          commit-message: ':package: Rebuild dist @ ${{ github.sha }}'
