# Based on the solution proposed here
#   https://sergiodxa.com/articles/github-actions-npm-publish/
#

name: Publish to NPM

on:
  release:
    types: [published]

env:
  CI: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
